# Generated by Django 5.0.6 on 2024-06-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="description",),
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
