# Generated by Django 5.0.6 on 2024-06-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_movie_description_movie_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="type",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
